COORDGEN-262
schrodinger/coordgenlibs pull request #80
Opened 2021-03-01 15:47 UTC by ZontaNicola

Always trust bond order for terminal metals (in other words never convert bonds to terminal atoms to zero order bonds), this means that terminal atoms are treated as part of the same molecule for depiction purposes, so the bond is always a standard length.

2021-03-02 21:04 UTC, d-b-w requested changes
Please add a test for this.

2021-03-03 05:09 UTC, greglandrum commented
I think having this option makes sense, but it does make the name of the option quite misleading - functionally it would no longer be `TreatAllBondsToMetalAsZOBs`.

I'm not sure how stable you need to keep the API, particularly with this new function, but ideally that option name could be changed to `TreatNonterminalBondsToMetalAsZOBs` or something equivalent. At the very least there should be some documentation for it.

2021-03-03 14:32 UTC, greglandrum commented
> > I think having this option makes sense, but it does make the name of the option quite misleading - functionally it would no longer be `TreatAllBondsToMetalAsZOBs`.
> > I'm not sure how stable you need to keep the API, particularly with this new function, but ideally that option name could be changed to `TreatNonterminalBondsToMetalAsZOBs` or something equivalent. At the very least there should be some documentation for it.
> 
> I think RDKit is the only place where this is used, if you're ok with updating the name, I'd just do that

No problem on the RDKit side. We haven't done a release that includes that functionality yet anyway (it's still on master).

2021-03-04 01:15 UTC, d-b-w commented
I see that you added a test, but I don't understand how it validates the new feature, since `setTreatNonterminalBondsToMetalAsZOBs()` is turned off in the test. Maybe the test should exercise both states?

Since this is only about terminal bonds, we don't expect this to help with https://jira.schrodinger.com/browse/CRDGEN-264, right?

2021-03-04 06:53 UTC, ZontaNicola commented
> I see that you added a test, but I don't understand how it validates the new feature, since `setTreatNonterminalBondsToMetalAsZOBs()` is turned off in the test. Maybe the test should exercise both states?
> 
> Since this is only about terminal bonds, we don't expect this to help with https://jira.schrodinger.com/browse/CRDGEN-264, right?

so now the treatment of non-terminal metals is controlled by the flag, while for terminal metals it's "always on", so the test for terminal metals doesn't need the flag to be set.
correct, this won't help with CRDGEN-264, nor does the setting/unsetting of the flag.

2021-03-05 09:29 UTC, ZontaNicola commented on sketcherMinimizer.cpp
> +    std::map<sketcherMinimizerAtom*, int> bondsToAtom;
the info in sketcherMinimizerAtom::bonds is not initialised until updateStructure is called later in the function, so unfortunately we can't use that nor sketcherMinimizerBond::isTerminal()

2021-03-06 01:03 UTC, d-b-w commented on sketcherMinimizer.cpp
> +    std::map<sketcherMinimizerAtom*, int> bondsToAtom;
thanks

2021-03-06 01:04 UTC, merged

2021-03-19 18:45 UTC, d-b-w commented
This change will require a version bump, because it changes the API of the library